### ISSUE TITLE
Running Readme Example

### ISSUE THREAD

**Issue by YomnaJehad** [bjornwallner/DockQ#4]
I'm following the instructions on the readme file, I clones the repo, moved to its directory, run the make command then I'm trying to run the example provided as well. but when I do an error comes up.
the example command: 
`bash ./DockQ.py examples/model.pdb examples/native.pdb`
The error that shows up
`import-im6.q16: attempt to perform an operation not allowed by the security policy 'PS' @ error/constitute.c/IsCoderAuthorized/408.
from: can't read /var/mail/Bio
./DockQ.py: line 6: syntax error near unexpected token 'ignore','
./DockQ.py: line 6: 'warnings.simplefilter('ignore', BiopythonWarning)'
`

**Comment by daniel1991zy** [comment]
You can try the python instead of bash

**Comment by daniel1991zy** [comment]
> I'm following the instructions on the readme file, I clones the repo, moved to its directory, run the make command then I'm trying to run the example provided as well. but when I do an error comes up. the example command: `bash ./DockQ.py examples/model.pdb examples/native.pdb` The error that shows up `import-im6.q16: attempt to perform an operation not allowed by the security policy 'PS' @ error/constitute.c/IsCoderAuthorized/408. from: can't read /var/mail/Bio ./DockQ.py: line 6: syntax error near unexpected token 'ignore',' ./DockQ.py: line 6: 'warnings.simplefilter('ignore', BiopythonWarning)' `

You can try the python instead of bash

**Comment by bjornwallner** [comment]
”bash” or actually ”bash$” as it is written in README is the prompt. The command should be: ./DockQ.py examples/model.pdb examples/native.pdb assuming DockQ is executable, otherwise: python ./DockQ.py examples/model.pdb examples/native.pdb
should work.

Cheers
Björn

On 18 Dec 2021, at 08:34, Yomna Jehad ***@***.***> wrote:

﻿

I'm following the instructions on the readme file, I clones the repo, moved to its directory, run the make command then I'm trying to run the example provided as well. but when I do an error comes up.
the example command:
bash ./DockQ.py examples/model.pdb examples/native.pdb
The error that shows up
import-im6.q16: attempt to perform an operation not allowed by the security policy 'PS' @ error/constitute.c/IsCoderAuthorized/408. from: can't read /var/mail/Bio ./DockQ.py: line 6: syntax error near unexpected token 'ignore',' ./DockQ.py: line 6: 'warnings.simplefilter('ignore', BiopythonWarning)'

—
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbjornwallner%2FDockQ%2Fissues%2F4&data=04%7C01%7Cbjorn.wallner%40liu.se%7C8ceac5ae36964e6f67d508d9c1f8e2ce%7C913f18ec7f264c5fa816784fe9a58edd%7C0%7C0%7C637754096979611948%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OnH7pgQoBMQRDMOzcCl%2BL4MQyYOYmThGchvOeonTU7U%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABAG3YBAR6O262O6XY2DR2LURQ2RZANCNFSM5KKLJCJQ&data=04%7C01%7Cbjorn.wallner%40liu.se%7C8ceac5ae36964e6f67d508d9c1f8e2ce%7C913f18ec7f264c5fa816784fe9a58edd%7C0%7C0%7C637754096979611948%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1xeitsmk6Z2WB%2BNTtaCQxj1d99cmr25axKs%2BTdXn%2BrU%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cbjorn.wallner%40liu.se%7C8ceac5ae36964e6f67d508d9c1f8e2ce%7C913f18ec7f264c5fa816784fe9a58edd%7C0%7C0%7C637754096979611948%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=xi3crN1UBryhoVW7WTC6NRGXjXyeWcN1hWWA0pqLimQ%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cbjorn.wallner%40liu.se%7C8ceac5ae36964e6f67d508d9c1f8e2ce%7C913f18ec7f264c5fa816784fe9a58edd%7C0%7C0%7C637754096979611948%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=6YL85n9mRSNDOJzagu2xJyxfRMmWhVGI1qOxzOf5uEs%3D&reserved=0>.
